In [1]:
import numpy as np
myarr = np.array([[1,2,3,4,5,7]], np.int64)
type(myarr[0,1])
#print(myarr)
# myarr[1]
# myarr.shape
# myarr.dtype


numpy.int64

In [16]:
# Conversion from other python structure
myarr = np.array([[1,2,3,4,5,7], [3,5,6,7,7,10],[6,7,23,4,6,55]])
myarr
myarr.dtype
print(myarr[1,2])


6


In [23]:
# Intrinsic numpy array creation
zeros =  np.zeros((2,5))
zeros
zeros.dtype
zeros.shape


dtype('float64')

In [26]:
rng= np.arange(15)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
lspace = np.linspace(1,50,10)
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [30]:
emp = np.empty((4,6))
emp
emp_like = np.empty_like(lspace)
emp_like

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [31]:
ide = np.identity(45)
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(45, 45))

In [2]:
arr = np.arange(99)
arr
arr.reshape(3,33)
arr.ravel()
arr.shape


NameError: name 'np' is not defined

In [5]:
import numpy as np
arr_2d = np.array([[1,2,4],[3,4,5]])
print(f"2D Array:\n{arr_2d}")


2D Array:
[[1 2 4]
 [3 4 5]]


In [6]:
import numpy as np
arr_1d = np.array([1,2,4])
print(f"1D Array:\n{arr_1d}")

1D Array:
[1 2 4]


In [12]:
import numpy as np
import time

In [15]:
start = time.time()
py_list = ([i*2 for i in range(1000000)])      
print("\n List Time taken: ", time.time() - start)

start = time.time()
np_arr = np.arange(1000000)*2
print("\n Numpy Time taken: ", time.time() - start)



 List Time taken:  0.08646559715270996

 Numpy Time taken:  0.006115436553955078


In [20]:
zeros = np.zeros((3,4))
zeros



array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
ones = np.ones((3,4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
full = np.full((3,4), 7)
full

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [22]:
sequence = np.arange(1,10,2)
sequence

array([1, 3, 5, 7, 9])

In [23]:
random = np.random.rand(3,4)
random


array([[0.82235357, 0.04205181, 0.29989281, 0.33641093],
       [0.50066556, 0.94831081, 0.92900452, 0.24716114],
       [0.76631824, 0.05197483, 0.57395052, 0.26229396]])

In [25]:
#  Vector , Metrix and Tensor
vector=np.array([1,2,3])
print(f"Vector:\n{vector}")

matrix=np.array([[1,2,3],[4,5,6]])
print(f"Matrix:\n{matrix}")

tensor=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(f"Tensor:\n{tensor}")

Vector:
[1 2 3]
Matrix:
[[1 2 3]
 [4 5 6]]
Tensor:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [6]:
import numpy as np
random = np.random.random((3,4))
random

array([[0.92843456, 0.76735793, 0.88629928, 0.06729359],
       [0.5644974 , 0.43969652, 0.91487923, 0.36328611],
       [0.99594292, 0.09164666, 0.52460966, 0.55314732]])

In [7]:
import numpy as np

In [8]:
sequence= np.arange(1,10,2)
sequence

array([1, 3, 5, 7, 9])

In [10]:
array = np.array([[1,2,3],[4,5,6]])
array
print("shape of array:",array.shape)
print("size of array:",array.size)
print("dimension of array:",array.ndim)
print("Dtype of array :" , array.dtype)

shape of array: (2, 3)
size of array: 6
dimension of array: 2
Dtype of array : int64


In [18]:
arr = np.arange(1,12,2)
arr

reshaped= arr.reshape(2,3)
reshaped

transpose = reshaped.T
transpose

flattened = reshaped.flatten()
flattened

raveled= reshaped.ravel()
raveled

array([ 1,  3,  5,  7,  9, 11])