In [1]:
import numpy as np
myarr = np.array([[1,2,3,4,5,7]], np.int64)
type(myarr[0,1])
#print(myarr)
# myarr[1]
# myarr.shape
# myarr.dtype


numpy.int64

In [16]:
# Conversion from other python structure
myarr = np.array([[1,2,3,4,5,7], [3,5,6,7,7,10],[6,7,23,4,6,55]])
myarr
myarr.dtype
print(myarr[1,2])


6


In [23]:
# Intrinsic numpy array creation
zeros =  np.zeros((2,5))
zeros
zeros.dtype
zeros.shape


dtype('float64')

In [26]:
rng= np.arange(15)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
lspace = np.linspace(1,50,10)
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [30]:
emp = np.empty((4,6))
emp
emp_like = np.empty_like(lspace)
emp_like

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [31]:
ide = np.identity(45)
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(45, 45))

In [35]:
arr = np.arange(99)
arr
arr.reshape(3,33)
arr.ravel()
arr.shape


(99,)