##Numpy Array Operations

In [1]:
import numpy as np

In [ ]:
arr=np.array([1,2,3,4,5])
print("Array:",arr[2:4])
print("Array:",arr[1:5:2])
print("Array:",arr[-1])

Array: [3 4]
Array: [2 4]
Array: 1


In [14]:
arr_2d = np.array([[1,2,3],[3,4,5],[5,6,7]])
arr_2d
arr_2d[1,2]
arr_2d[:2,1:3]
arr_2d[:,1]

array([2, 4, 6])

Sorting

In [ ]:
import numpy as np


array([1, 2, 3, 4, 5])

In [ ]:
unsort= np.array([3,1,2,5,4])
np.sort(unsort)


array([1, 2, 3, 4, 5])

In [28]:
arr_2d_unsort= np.array([[1,2],[4,6],[7,8]])
np.sort(arr_2d_unsort,axis=1)

array([[1, 2],
       [4, 6],
       [7, 8]])

Filtering

In [31]:
filter_arr= np.array([1,2,3,4,5])
filter_arr[filter_arr>2]
even_number= filter_arr[filter_arr%2==0]
print("Even numbers:",even_number)

Even numbers: [2 4]


Filter with Mask

In [42]:

numbers= np.array([1,2,3,4,5,6,7,8,9,10])


mask = numbers>2
print("Mask:",numbers[mask])

Mask: [ 3  4  5  6  7  8  9 10]


Fancy Indexing vs np.where()

In [ ]:
incidies =[0,2,4]
print("Incidies:",numbers[incidies])

where_result = np.where(numbers>2)
print("Where result:",numbers[where_result])



Incidies: [1 3 5]
Where result: [3 4 5]


Condition Array

In [50]:
numbers=np.array([1,2,3,4,5,6,7,8,9,10])
condition_array = np.where(numbers > 4,numbers*2,numbers)
print("Condition array:",condition_array)

Condition array: [ 1  2  3  4 10 12 14 16 18 20]


Adding and removing data

In [53]:
array = np.array([1,2,3])
array2 = np.array([4,5,6])
concat_array = np.concatenate((array,array2))
print("Concatenated array:",concat_array)

Concatenated array: [1 2 3 4 5 6]


array comptibility

In [55]:
a= np.array([1,2,3])
b= np.array([4,5,6])
c= np.array([7,8,9])
print("compatible shapes:",a.shape == b.shape)

compatible shapes: True


In [64]:
import numpy as np
original_array = np.array([[1,2,3],[4,5,6]])
new_row = np.array([[7,8,9]])
result_array = np.vstack((original_array,new_row))
print("Resultant array after adding new row:\n",result_array)

# new_col = np.array([[7],[8]])
new_col = np.array([[7],[8]])

result_array1 = np.hstack((original_array,new_col))
print(result_array1)

Resultant array after adding new row:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 7]
 [4 5 6 8]]


In [70]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,20]])
deleted = np.delete(arr[1],2)
print(deleted)

[ 6  7  9 20]
